/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CodeBlockComponent: typeof import('./components/Editor/CodeBlockComponent.vue')['default']
    Editor: typeof import('./components/Editor.vue')['default']
    IconEdit: typeof import('lucide-vue-next')['Edit']
    IconHome: typeof import('lucide-vue-next')['Home']
    IconMinus: typeof import('lucide-vue-next')['Minus']
    IconPlus: typeof import('lucide-vue-next')['Plus']
    IconTarget: typeof import('lucide-vue-next')['Target']
    ItemLayout: typeof import('./layouts/ItemLayout.vue')['default']
    ItemList: typeof import('./components/ItemList.vue')['default']
    Link: typeof import('./components/Link.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NButtonGroup: typeof import('naive-ui')['NButtonGroup']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NGlobalStyle: typeof import('naive-ui')['NGlobalStyle']
    NH3: typeof import('naive-ui')['NH3']
    NIcon: typeof import('naive-ui')['NIcon']
    NLoadingBarProvider: typeof import('naive-ui')['NLoadingBarProvider']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NPageHeader: typeof import('naive-ui')['NPageHeader']
    NSpace: typeof import('naive-ui')['NSpace']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TagsAutoComplete: typeof import('./components/TagsAutoComplete.vue')['default']
    TheHeader: typeof import('./components/TheHeader.vue')['default']
    Versions: typeof import('./components/Versions.vue')['default']
  }
}
