/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CodeBlockComponent: typeof import('./components/Editor/CodeBlockComponent.vue')['default']
    Editor: typeof import('./components/Editor.vue')['default']
    IconFile: typeof import('lucide-vue-next')['File']
    IconPlus: typeof import('lucide-vue-next')['Plus']
    IconSave: typeof import('lucide-vue-next')['Save']
    IconSearch: typeof import('lucide-vue-next')['Search']
    IconType: typeof import('lucide-vue-next')['Type']
    ItemLayout: typeof import('./layouts/ItemLayout.vue')['default']
    ItemList: typeof import('./components/ItemList.vue')['default']
    Link: typeof import('./components/Link.vue')['default']
    NAutoComplete: typeof import('naive-ui')['NAutoComplete']
    NButton: typeof import('naive-ui')['NButton']
    NButtonGroup: typeof import('naive-ui')['NButtonGroup']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NDivider: typeof import('naive-ui')['NDivider']
    NDynamicTags: typeof import('naive-ui')['NDynamicTags']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NGlobalStyle: typeof import('naive-ui')['NGlobalStyle']
    NH3: typeof import('naive-ui')['NH3']
    NIcon: typeof import('naive-ui')['NIcon']
    NInput: typeof import('naive-ui')['NInput']
    NInputGroup: typeof import('naive-ui')['NInputGroup']
    NLoadingBarProvider: typeof import('naive-ui')['NLoadingBarProvider']
    NMenu: typeof import('naive-ui')['NMenu']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NPageHeader: typeof import('naive-ui')['NPageHeader']
    NSelect: typeof import('naive-ui')['NSelect']
    NSkeleton: typeof import('naive-ui')['NSkeleton']
    NSpin: typeof import('naive-ui')['NSpin']
    NTag: typeof import('naive-ui')['NTag']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TagsAutoComplete: typeof import('./components/TagsAutoComplete.vue')['default']
    TheHeader: typeof import('./components/TheHeader.vue')['default']
    Versions: typeof import('./components/Versions.vue')['default']
  }
}
